{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggeasy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggeasy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggeasy/ggeasy_{{ version }}.tar.gz
  sha256: 2655c7cc266e67b13cbb586c984d2c049affb237b67543dc7757b64a4b98ddc6

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-rlang
  run:
    - r-base
    - r-ggplot2
    - r-rlang

test:
  commands:
    - $R -e "library('ggeasy')"           # [not win]
    - "\"%R%\" -e \"library('ggeasy')\""  # [win]

about:
  home: https://github.com/jonocarroll/ggeasy
  license: GPL-2.0-or-later
  summary: Provides a series of aliases to commonly used but difficult to remember 'ggplot2' sequences.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
